In [1]:
import pandas as pd
df = pd.read_csv("../data/cybersecurity.csv")

In [2]:
df.head()

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign

In [3]:
df.isnull().sum()

timestamp                 0
src_ip                    0
dst_ip                    0
src_port                  0
dst_port                  0
protocol                  0
bytes_sent                0
bytes_received            0
user_agent                0
url                    3232
is_internal_traffic       0
label                     0
attack_type               0
dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            10000 non-null  str
 1   src_ip               10000 non-null  str
 2   dst_ip               10000 non-null  str
 3   src_port             10000 non-null  int64
 4   dst_port             10000 non-null  int64
 5   protocol             10000 non-null  str
 6   bytes_sent           10000 non-null  int64
 7   bytes_received       10000 non-null  int64
 8   user_agent           10000 non-null  str
 9   url                  6768 non-null   str
 10  is_internal_traffic  10000 non-null  bool
 11  label                10000 non-null  int64
 12  attack_type          10000 non-null  str
dtypes: bool(1), int64(5), str(7)
memory usage: 2.6 MB

In [5]:
df.describe()

           src_port      dst_port    bytes_sent  bytes_received         label
count  10000.000000  10000.000000  1.000000e+04    1.000000e+04  10000.000000
mean   27052.223700   2027.280500  1.412572e+05    2.620883e+05      0.040000
std    20978.783832   6769.141395  2.128140e+06    3.767695e+06      0.195969
min       21.000000      5.000000  1.700000e+01    3.000000e+00      0.000000
25%     6092.250000     25.000000  7.148250e+03    1.096075e+04      0.000000
50%    25431.500000    443.000000  2.181550e+04    3.747300e+04      0.000000
75%    45215.750000   1433.000000  6.509525e+04    1.213795e+05      0.000000
max    65524.000000  65491.000000  1.391704e+08    2.914830e+08      1.000000